version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: white_tariff
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_net

  nosql:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root        # 👤 MongoDB root user
    #   MONGO_INITDB_ROOT_PASSWORD: rootpass    # 🔐 MongoDB root password
    networks:
      - app_net

volumes:
  mysql_data:
  mongo_data:

networks:
  app_net:
    driver: bridge
