version: '3.8'

services:
  # app:
  #   build: .
  #   container_name: nestjs_app
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - DB_HOST=mysql
  #     - DB_PORT=3306
  #     - DB_USER=root
  #     - DB_PASSWORD=0998
  #     - DB_NAME=white_tariff_api
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - .:/usr/src/app
  #     - ./.env:/usr/src/app/.env
  #     - /usr/src/app/node_modules
  #   command: npm run start:dev

  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0998
      MYSQL_DATABASE: white_tariff
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  nosql:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data: